version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecms
      MYSQL_PASSWORD: ecms
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecommerce_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  config-server:
    build: ./Config-Server
    container_name: config-server
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - ecommerce_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  authentication:
    build: ./Authentication
    container_name: authentication
    restart: always
    ports:
      - "8084:8084"
    networks:
      - ecommerce_network

  category:
    build: ./Category
    container_name: category
    restart: always
    ports:
      - "8085:8085"
    networks:
      - ecommerce_network

  product:
    build: ./Product
    container_name: product
    restart: always
    ports:
      - "8086:8086"
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    driver: bridge

volumes:
  mysql_data:
