spring:
  application:
    name: payment
  config:
    import: optional:configserver:http://localhost:8080/

razorpay:
  key:
    id: rzp_test_p8ORl58CBKF09o
  secret:
    key: oqql3HGWO7Ubvln8DwLIH9ev