spring:
  application:
    name: category
  config:
    # Docker Config-Server
#    import: optional:configserver:http://config-server:8080
    # Local Config-Server
    import: optional:configserver:http://localhost:8080/