spring:
  application:
    name: email

  mail:
    host: 
    port: 
    username: 
    password: 
    protocol: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8092
