server:
  port: ${server.port}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # Local Datasource
  datasource:
    url: ${database-url}
    username: ${database-username}
    password: ${database-password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Docker Datasource
#  datasource:
#  url: ${database-url}
#  username: ${database-username}
#  password: ${database-password}
#  driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${github-client_id}
            client-secret:  ${github-client-secret}
          google:
            client-id: ${google-client-id}
            client-secret: ${google-client-secret}

jwt:
  access-secret: ${jwt-access-secret}
  refresh-secret: ${jwt-refresh-secret}
  access-expiry: ${access-token-expiry}
  refresh-expiry: ${refresh-token-expiry}

user:
  password-expiry: ${password-expiry}

