server:
  port: 8084

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://mysql:3306/ecommerce
    username: ecms
    password: ecms
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 
            client-secret: 
          google:
            client-id: 
            client-secret: 
