server:
  port: 8084

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # Local Datasource
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/ecms_local
    username: root
    password: Online#9900
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Docker Datasource
#  datasource:
#    url: jdbc:mysql://mysql:3306/ecommerce
#    username: ecms
#    password: ecms
#    driver-class-name: com.mysql.cj.jdbc.Driver


  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 
            client-secret: 
          google:
            client-id: 
            client-secret: 

jwt:
  access-secret: 
  refresh-secret: 
  access-expiry: 600000     # 10 minutes after access expiry should be able to generate new access using not expired refresh
  refresh-expiry: 1200000   # 20 minutes after refresh expiry login required if password not expired to get the new access & refresh

user:
  password-expiry: 1800000  # 30 minutes after password expiry no access or refresh re issue, have to change the password

