server:
  port: 8085

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

datasource:
  url: jdbc:mysql://turntable.proxy.rlwy.net:39690/railway?useSSL=false&allowPublicKeyRetrieval=true
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  driver-class-name: com.mysql.cj.jdbc.Driver

