server:
  port: 8085

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://root:RkfbJSyYIDcbPhhfEvJfaIxpNjcLEuGL@turntable.proxy.rlwy.net:39690/railway
    username: root
    password: RkfbJSyYIDcbPhhfEvJfaIxpNjcLEuGL
    driver-class-name: com.mysql.cj.jdbc.Driver
