server:
  port: 8087

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # Local Datasource
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/ecms_local
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Docker Datasource
#  datasource:
#    url: jdbc:mysql://mysql:3306/ecommerce
#    username: ecms
#    password: ecms
#    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: 
  expiry: 86400000 # 1 day in ms
