server:
  port: ${server.port}
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # Local Datasource
  datasource:
    url: ${database-url}
    username: ${database_username}
    password: ${database_password}
    driver-class-name: com.mysql.cj.jdbc.Driver