server:
  port: 8088

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # Local Database
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/ecms_local
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Docker Datasource
#  datasource:
#    url: jdbc:mysql://mysql:3306/ecommerce
#    username: ecms
#    password: ecms
#    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      group_id: ecommerce
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'

    consumer:
      bootstrap-servers: localhost:9092
      group_id: ecommerce
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'

razorpay:
  key:
    id: 
  secret:
    key: 
