name: CI & Run Spring Boot Microservices via Scripts

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build All Microservices
        run: |
          for dir in Authentication Caching Category Config-Server Customer Emailing Invoicing Messaging Order Payment Product; do
            echo "Building $dir..."
            cd $dir
            if [ -f "pom.xml" ]; then mvn clean install -DskipTests; fi
            if [ -f "build.gradle" ]; then ./gradlew build -x test; fi
            cd ..
          done

      - name: Make all scripts executable
        run: chmod +x Scripts/*.sh

      - name: Start Kafka/Zookeeper
        run: |
          bash Scripts/zookeeper.sh
          bash Scripts/kafka_server.sh
          bash Scripts/kafka_consumer.sh

      - name: Start Microservices
        run: |
          bash Scripts/configs.sh
          bash Scripts/authentication.sh
          bash Scripts/product.sh
          bash Scripts/order.sh
          bash Scripts/payment.sh
          bash Scripts/emailing.sh
          bash Scripts/invoicing.sh
          bash Scripts/messaging.sh
          bash Scripts/customer.sh
          bash Scripts/category.sh
          bash Scripts/caching.sh

      - name: Wait for services to start
        run: sleep 30

      - name: Health Check / Integration Tests
        run: |
          curl --fail http://localhost:8080/actuator/health || echo "Authentication failed"
          curl --fail http://localhost:8081/actuator/health || echo "Product failed"
          curl --fail http://localhost:8082/actuator/health || echo "Order failed"
          # Add other ports & endpoints as needed

      - name: Run Functional Test Script (Optional)
        run: |
          if [ -f Scripts/test.sh ]; then bash Scripts/test.sh; fi
